import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);

import { Roboto } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const roboto = Roboto({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Book Borrowing Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${roboto.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
